### PR TITLE
Add support for append and prepend on collection_select (fixes #428)

### LINKED ISSUE #428: `:append` and `:prepend` not applied to collection selects.
If the user provides `:append` and `:prepend` options to `select`, the text/HTML will be appended or prepended to the control. If the user provides those options to `collection_select` or `grouped_collection_select`, they have no effect. I don't see why this should be inconsistent.

I'm not sure whether this is a bug or a feature request.

At ae08c5b1 (Feb 15, 2014), specifically https://github.com/bootstrap-ruby/bootstrap_form/commit/ae08c5b1fb224612b0eb3d2f7433f1dca8bf1790#diff-d858d9de5eda99f11a7840b6c015c89eR8 and https://github.com/bootstrap-ruby/bootstrap_form/commit/ae08c5b1fb224612b0eb3d2f7433f1dca8bf1790#diff-d858d9de5eda99f11a7840b6c015c89eR40, the handling of `select` and `collection_select` were moved out of the "generic" definition of the `bootstrap_form` helpers. In doing so, it looks like they both lost `:append` and `:prepend`.

It looks like it was fixed for `select` with PR #327 (Apr 24, 2017), but not for the other select methods.

### PR DESCRIPTION
**Pull request by judylovesruby**
Hello,
thanks a lot for creating this gem! 
Today I would have needed a `collection_select` with `prepend` and noticed that this does not work yet.
Here's a fix for it. I hope everything's alright and would be happy if it got merged :slightly_smiling_face: 
Best,
Judith

### CODE REVIEW

**Review by lcreid — COMMENTED** [review]
Thanks for this PR. It's very much appreciated. I haven't yet had time to dig into it -- the PR looks good but it raises some questions in my mind about other methods that don't support prepend and append. If I recall correctly, Bootstrap 4 had specific classes that didn't apply to all types of form elements, but I could be wrong about that. 

Do you think there are other methods that don't support prepend and append, but could and should?

**Comment by judylovesruby** [comment]
I don't consider myself a poweruser of bootstrap or bootstrap_form, so I'm not sure. But the only thing I found now was grouped_collection_select, which you mention in the linked issue. 
At least for the selects there are examples in the Bootstrap 5 documentation: https://getbootstrap.com/docs/5.0/forms/input-group/ . And the "ordinary" select of bootstrap_form already handles prepend and append :)

**Comment by lcreid** [comment]
Great. Thanks for looking into this. I'll merge this shortly.

Thanks for your patience. I don't actually use this gem at the moment, so it always takes me a while to get back up to speed. Thank you for you support and efforts to improve the gem.

**Review by lcreid — APPROVED** [review]
Thanks for this. It looks good. We really appreciate your contribution.

**Comment by judylovesruby** [comment]
Thanks for merging this @lcreid! I saw you also did some other changes lately. Do you plan to release more changes together?

**Comment by lcreid** [comment]
I was trying to get another change in, but obviously I haven't managed that yet. I'll try to do a release soon, but in the meantime you can temporarily change your `Gemfile` to use this:

```
gem "bootstrap_form", git: "https://github.com/bootstrap-ruby/bootstrap_form.git", branch: "main"
```

Thanks for your patience, and your PR. We really appreciate your contribution.

**Comment by judylovesruby** [comment]
Okay, thanks for letting me know :slightly_smiling_face: 
I usually prefer not to include links to repositories in the Gemfile, since then bundler-audit will not be able to warn me in case of CVEs. But I can do it as temporary workaround.

**Comment by lcreid** [comment]
That's a good point. I managed to release version 5.1, including your PR, yesterday. Thanks again for your contribution!

**Comment by judylovesruby** [comment]
Thank you :slightly_smiling_face:

**Pull request merged**
