### PR TITLE
Simplify rendering of file_field for Bootstrap 5. Fixes #572

### LINKED ISSUE #572: Simplify rendering of file_field for Bootstrap 5 alpha 3
Bootstrap 5 alpha 3 can now render a very nice looking file selector without needing additional classes or extra markup.

Current markup for `f.file_field :image`:

```
<div class="mb-3">
  <label class="form-label" for="workout_video_image">Image</label>
  <div class="form-file">
    <input class="form-file-input" type="file" name="workout_video[image]" id="workout_video_image">
    <label class="form-label form-file-label" for="workout_video_image">Choose file</label>
  </div>
</div>
```

Can be simplified to:

```
<div class="mb-3">
  <label class="form-label" for="workout_template_image">Image</label>
  <input class="form-control" type="file" name="workout_video[image]" id="workout_video_image">
</div>
```

More information can be found here: https://v5.getbootstrap.com/docs/5.0/forms/form-control/#file-input

I'd like to try to make this change myself, but if someone else is in a position to pick this up feel free to do so.

### PR DESCRIPTION
**Pull request by thimo**
Bootstrap 5 can now render a very nice looking file selector without needing additional classes or extra markup. This PR cleans up the generated HTML and tests. See https://github.com/bootstrap-ruby/bootstrap_form/issues/572.

At the same time, to get the demo app running, I've made these changes:

- remove the reference in manifest.js to the non existent folder `../images`
- update the Bootstrap 5 CDN links

### CODE REVIEW

**Comment by thimo** [comment]
PS: this is how the updated file upload control looks. When you select a file, the filename will be displayed in place of "No file chosen".

CleanShot 2021-04-06 at 19 10 01@2x

**Review by lcreid — APPROVED** [review]
The markup really is a lot cleaner, isn't it? Thanks again for all the work you've done of late! You rock.

**Comment by thimo** [comment]
I've rebased my branch to the current bootstrap-5 branch so tests would run, and after that fixed one Rubocop offence.

**Review by lcreid — APPROVED** [review]
Looks good!

**Pull request merged**
