### PR TITLE
Add `generate_validation_failed` method to not override help text

### PR DESCRIPTION
**Pull request by antpaw**
User will see "help" and "validation error" text.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR! I appreciate the fact that you added tests. 👍 

Just to be clear, this is a fix for #284, right? Also, this is a significant change in behavior, so could you add a CHANGELOG entry?

**Comment by antpaw** [comment]
Hi, it looks like this could be a fix #284. I didn't add tests, (just modified them) because it looks to me that existing tests cover all case. I've added a changelog entry because now i know that you consider this as a "change in behaviour", i though this would go under bug fix, but was not sure.

Maybe it's better to port this into the "bootstrap-v4" release because this release will also have breaking changes.

This branch contains both of them. https://github.com/antpaw/rails-bootstrap-forms/tree/bootstrap-v4-help-with-error

**Comment by jsaraiva** [comment]
Hello!

Will this be merged eventually? I just ran into this problem too, in a password input field with validation errors and a help message describing its complexity requirements. :-(

Cheers!

**Comment by lcreid** [comment]
Thanks for bringing this to my attention. It looks like in the early days of Bootstrap 4 migration, this PR got lost in the transition.

@antpaw would you be interested in seeing what has to be done to make this PR merge against current master?

**Comment by antpaw** [comment]
Hi, it looks like I just need to change `help-block` class to `form-text text-dange` ([migration guide](https://getbootstrap.com/docs/4.3/migration/#forms-1)) and do some testing. I think I can look into it soon

**Comment by antpaw** [comment]
Okay just forced pushed a commit to the same branch (from this pr). I couldn't run the project until I did all the clean up that I have also pushed to a different branch. [Maybe you also want to merge that as well.](https://github.com/bootstrap-ruby/bootstrap_form/pull/530)

**Comment by lcreid** [comment]
Thanks. I much appreciate it. Don't worry about the Travis checks failing. At least some are because of Travis. And it looks like most of them are going to disappear in the next few weeks when we update our support matrix with the release of Rails 6.

**Comment by donv** [comment]
Hi @antpaw !

Thanks for the PR!  Would you still like this merged?  If so, please rebase against main.  If not, I will close the PR.

**Comment by antpaw** [comment]
hey, done

**Comment by donv** [comment]
Thanks!

**Pull request merged**
