### PR TITLE
Add add_control_col option on form_group.

### PR DESCRIPTION
**Pull request by ThomasSevestre**
Add add_control_col option on form_group.
This options allows caller to add classes on control col div, in addtion to the classes defined on the form.

### CODE REVIEW

**Comment by ThomasSevestre** [comment]
I'll make danger happy if you want to merge

**Comment by lcreid** [comment]
Thanks for the contribution! Sorry for the slow response. 

Can you give one or two examples where you would use this option, please? The only ones I can think of, I would just code the `<div class="form-group">` in HTML, and put the `bootstrap_form` helper inside the `div`, but I'm probably not thinking of your use case.

**Comment by ThomasSevestre** [comment]
Here are my use cases:
First exemple, to display or edit complex attributes.
Second exemple to display a boolean field with a switch aligned with other inputs

    = bootstrap_form_for(object, layout: :horizontal, label_col: "col-2", control_col: "col-10") do |f|
    
      - f.custom_control :strange_attribute, add_control_col: 'form-control-plaintext'
       | whatever
    
      - f.custom_control :checkbox_attribute, add_control_col: 'checkbox-with-switch-style'
        = f.check_box_without_bootstrap :checkbox_attribute
        label for="object_checkbox_attribute"

**Comment by lcreid** [comment]
I haven't forgotten about you. Sorry for the delayed response, but we're all volunteers here so other things have to take priority sometimes. 

For some time we've been a bit concerned about the large number of options on the helpers. I'd like to take a week to see if I can come up with a proposal to organize the options to the helpers, so it's more obvious how to handle cases like yours. In the meantime, I appreciate your patience, and feel free to submit suggestions.

**Comment by ThomasSevestre** [comment]
No worries. Please, take your time

**Comment by lcreid** [comment]
I think I'm still misunderstanding what you're asking. Doesn't the `wrapper` or `wrapper_class` option do what you're asking? See the README at: https://github.com/bootstrap-ruby/bootstrap_form#additional-form-group-attributes.

**Comment by ThomasSevestre** [comment]
This PR add allow one to add classes on the control wrapper of horizontal forms

    <div class="form-group">
      <label class="col-sm-2 form-control-label" for="user_email">Email</label>
      <div class="col-sm-10 **here-is-the-added-class**">
        <input class="form-control-plaintext" id="user_email" name="user[email]" readonly="readonly" type="text" value="test@email.com"/>
      </div>
    </div>

**Comment by ThomasSevestre** [comment]
I named the attribute `add_control_col` because it adds a class to the attribute `control_col` of the bootstrap_form ( https://github.com/bootstrap-ruby/bootstrap_form#horizontal-forms )

I prefer `add_control_col_class`.
Can you confirm the new name ?

Thanks

**Comment by lcreid** [comment]
Please change the name of the option from `add_control_col` to `add_control_call_class` and update the PR (with documentation and tests, of course).

**Comment by lcreid** [comment]
Sorry for the delay. We wanted to release 4.0.0 before I merged your PR. We finally released yesterday. I hope to do a release every six weeks if there's anything to release, but I may do one sooner for your PR.

Thanks for the PR, and your patience waiting for this merge.

**Pull request merged**
