### PR TITLE
Add error_key field option. Closes #318 (v3)

### LINKED ISSUE #318: collection_select validation errors missing
Suppose a have a model

Class A <  ApplicationRecord
end

with attributes id and title

and a model

Class B <  ApplicationRecord
   belongs_to :a 
   validates_presence_of :a 
end

and a form 
- bootstrap_form_for @b do |f|
  = f.collection_select :a_id, A.all, :id, :title, {prompt: "Select one}

and a code in controller
 @b.update(params.require(:b).premit(:a_id))

I don't see validation errors when user leaves selection blank. This is because
@b.errors.messages[:a] is set, and bootstrap_forms expects @b.errors.messages[:a_id] to be set.

The same problem with habtm relation and collection_select with {multiple: true}.

If i change my code to 
- bootstrap_form_for @b do |f|
  = f.collection_select :a, A.all, :id, :title, {prompt: "Select one}

 @b.update(params.require(:b).premit(:a))

a get an error "got string, A expected"

### PR DESCRIPTION
**Pull request by mattbrictson**
This is a cherry-pick of #333 onto master instead of v4.

### CODE REVIEW

**Comment by sebfie** [comment]
Hello, I think it's a right pr to merge :)

**Comment by donv** [comment]
@mattbrictson This looks like a good change.  Can you rebase onto main?

**Comment by donv** [comment]
The demo app was moved from `test/dummy` to `demo` so it is a bit difficult to rebase the change.

@mattbrictson Do you still want this change?.

**Comment by mattbrictson** [comment]
I have forgotten the context or need that motivated me to open this PR. It is safe to say I no longer need it. I will close.

**Pull request closed without merging**
