### PR TITLE
Add bootstrap form with helper on rails 5.1

### PR DESCRIPTION
**Pull request by chukitow**
On Rails 5.1  form_tag & form_for were unified in form_with, I'm adding the helper when using Rails >= 5.1

### CODE REVIEW

**Comment by chukitow** [comment]
Didn't noticed this feature is in progress https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/346, closing PR

**Comment by lcreid** [comment]
PR #346 adds support for `form_with` with extensive testing. [Disclaimer: I submitted that PR.] It now has merge conflicts which I'll resolve once we get a few of the other pending PRs merged into master.

**Comment by lcreid** [comment]
PR #346 was replaced by PR #369.

**Comment by lcreid** [comment]
@mattbrictson , could you please review this one, as I have an obvious conflict of interest. :-) If I understand correctly, this PR was submitted against master back when master was still Bootstrap 3.

**Comment by mattbrictson** [comment]
Closed in favor of #369.

**Pull request closed without merging**
