### PR TITLE
Update hide_class from sr-only to visually-hidden

### PR DESCRIPTION
**Pull request by aki77**
https://getbootstrap.com/docs/5.0/migration/#helpers

### CODE REVIEW

**Comment by donv** [comment]
This seems like a good change.  Will merge when check succeed.

**Comment by donv** [comment]
Checks for "danger" failed.  Maybe rebase?

**Comment by donv** [comment]
I fixed the danger failure on master.  All the other checks succeeded, so I'll merge.

**Comment by aki77** [comment]
Thanks!

**Pull request merged**
