### PR TITLE
Enable include hidden

### PR DESCRIPTION
**Pull request by a5-stable**
Fixes https://github.com/bootstrap-ruby/bootstrap_form/issues/215

Enable include_hidden option with collection_check_boxes:

### CODE REVIEW

**Comment by donv** [comment]
This PR looks good, but the "danger" linting fails.  Anybody an idea why the linting fails?

**Comment by a5-stable** [comment]
Thanks for checking!

#625 seems to mention this failure at danger gem.

**Comment by donv** [comment]
I have committed the suggested fix for `danger`.  @a5-stable could you rebase this PR to test the fix?

**Comment by a5-stable** [comment]
@donv 
Thank you for quick fixing.
Synced to HEAD.

**Comment by donv** [comment]
I committed a workflow change to enable secrets for fork-PRs for `danger`.  Could you rebase again and see if it helps?  If it doesn't help I will do a manual review of this PR.

**Comment by a5-stable** [comment]
@donv 
Thanks!
I did but workflow seems failed at loading danger.

**Comment by donv** [comment]
Thanks @a5-stable for the PR and the CHANGELIG entry!  The problem with `danger` will take longer to resolve, so I'll merge this PR now.

**Pull request merged**
